---
- name: Include Ubuntu 20 specific tasks
  ansible.builtin.include_tasks:
    file: ub20.yml
  when:
    - ansible_facts.distribution == "Ubuntu"
    - ansible_facts.distribution_major_version | int <= 20

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ ansibledev_apt_dependencies }}"
    state: present
    update_cache: true
  when: ansible_facts.os_family == "Debian"

- name: Enable crb repo
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  when: ansible_facts.os_family == "RedHat"

- name: Install system packages
  ansible.builtin.dnf:
    name: "{{ ansibledev_dnf_dependencies }}"
    state: present
    update_cache: true
  when: ansible_facts.os_family == "RedHat"

- name: Create venvs dir
  ansible.builtin.file:
    path: ~/.virtualenvs
    mode: "0775"
    state: directory
  become: false

- name: Install ansible packages in virtual env
  ansible.builtin.pip:
    name: "{{ ansibledev_pip_pkgs }}"
    state: present
    virtualenv: ~/.virtualenvs/ansible
    virtualenv_command: |
      {% if ansible_facts.distribution == "Ubuntu" and ansible_facts.distribution_major_version | int <= 20 %}
      {{ ansibledev_min_python }} -m venv
      {% else %}
      virtualenv
      {% endif %}
  become: false
