---
name: CI
on:
  # trunk-ignore(yamllint/empty-values)
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Cache Docker images
        uses: ScribeMD/docker-cache@0.5.0
        with:
          key: docker-${{ runner.os }}-${{ hashFiles('molecule/default/molecule.yml') }}

      - name: Install test dependencies
        run: pip install -r dev-requirements.txt

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
