---
name: CI
on:
  # trunk-ignore(yamllint/empty-values)
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest

    permissions:
      checks: write   # For trunk to post annotations
      contents: read  # For repo checkout

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: pip install -r dev-requirements.txt

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
