---
name: CI
on:
  # trunk-ignore(yamllint/empty-values)
  pull_request:
  push:
    branches: [main]

permissions: read-all

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      # - name: Set up Python 3.
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.x'

      - name: Install test dependencies
        run: pip install -r dev-requirements.txt

      - name: Run Molecule tests
        run: molecule test
        # env:
        #   PY_COLORS: '1'
        #   ANSIBLE_FORCE_COLOR: '1'
